### PR TITLE
Making this repository as a library

### PR DESCRIPTION
**Pull request by Trismegiste**
Hello, 

I've converted your functional PHP to OOP for my project (after struggling with the async Pawl client).

I took the liberty to use your username as a package name (for publishing to Packagist, in the future) and the namespace.
That's the least I can do given how your code helped me a lot.
There's also a minimal testing (your example.php was converted to a phpunit class).

There are some design flaws in this fast conversion, and probably a need for a better use for exceptions (specially the connection).

Hope this helps, and again : thanks ! :heart: 

If you think your library doesn't require OOP, I understand and feel free to dismiss this PR.

Florent

### CODE REVIEW

**Comment by paragi** [comment]
Hi Florent

Thank you for a much needed update! It is absolutely the right way to go.
I will look into the merge, as soon as possible. 
I’m curious about the flaw in “fast conversion” I look forward to digging into it.

BR Simon Rigét

**Comment by Trismegiste** [comment]
Hello,

Glad you like it.
When I was talking about design flaws, I just wonder if I should use Exception everywhere or not.

Finally, I've decided yes. No return codes or strings by reference (I kept them anyway).
Now using this Client class is simple and straightforward.

I've also add a websocket server for test only (in the require-dev composer section) since the server "echo.websocket.org" is no longer available.

And I add some documentations.

**Comment by paragi** [comment]
That's a good move :)
However i think it's important to have an example of a test against a completely different implementation. Preferable one that is up to the latest standards. I will look into it, when time permits. You are welcome to choose one too, if you you have a preference? 
Thanks for your contribution. It's appreciated.

**Comment by paragi** [comment]
Don't forget to add your name somewhere in the code, as a contributor ;)

**Comment by Trismegiste** [comment]
Hello 

> i think it's important to have an example of a test against a completely different implementation. Preferable one that is up to the latest standards.

Not sure what you mean. 
I'm relying on Ratchet library ( https://github.com/ratchetphp/Ratchet ) to implement the test echo server.
I'm pretty sure it's the most advanced implementation for PHP since hoaproject/Websocket was deprecated / defunct.

That being said, I do not test all websocket functionalities and honestly I don't fully understand all the intricacies of this protocol but it runs smoothly for my project.

**Comment by paragi** [comment]
I've decided to merge the PR now, rather than doing a proper review, in the hope that all i ok ;)
This is a nice job. Thank you for your contribution.
BR Simon

**Comment by Trismegiste** [comment]
Thank you for your confidence.
I think the next step is to release a v1.0.0 version and publish the repo on Packagist for Composer usage.

Next week, I'll test this library in real conditions, I let you know if I encounter some bugs.

**Pull request merged**
